apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-004612-yxtnbu8tkyfh-service
spec:
  selector:
    app: enterprise-system-20260507-004612-yxtnbu8tkyfh
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
